version: '2.2'
services:
  kibana:
      image: docker.elastic.co/kibana/kibana:6.6.1
      container_name: kibana
      ports:
      - 5601:5601
      environment:
        - "ELASTICSEARCH_URL=http://elasticsearch1:9200"
      networks:
        - esnet
networks:
  esnet: