version: "3.3"

services:

  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017
    networks:
      - oms
    volumes:
      - mongodb-vol:/data/db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.role == true

volumes:
  mongodb-vol:
    external: true

networks:
  oms:
    external: true
